In [5]:
import numpy as np

In [ ]:
arr = np.arange(225).reshape(5,15,3)
arr

In [ ]:
arr[:,0,:]

In [11]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [12]:
arr[:,0:1,0:2]

array([[[  0,   1]],

       [[ 45,  46]],

       [[ 90,  91]],

       [[135, 136]],

       [[180, 181]]])

In [14]:
arr[2][2][1]

97

In [16]:
arr[0][::-1]

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [20]:
arr[0][::-1,::-1]                       # order reverse

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

Sorting in array

In [9]:
import numpy as np
arr1 = np.array([2,3,467,889,43,45,34])
arr2 = np.array([[45,76,89,3,43],[45,7,89,45,65]])
arr2

array([[45, 76, 89,  3, 43],
       [45,  7, 89, 45, 65]])

In [12]:
arr1.sort()
arr1

array([  2,   3,  34,  43,  45, 467, 889])

In [13]:
arr2.sort()
arr2

array([[ 3, 43, 45, 76, 89],
       [ 7, 45, 45, 65, 89]])

In [14]:
arr2[::-1,::-1]

array([[89, 65, 45, 45,  7],
       [89, 76, 45, 43,  3]])

In [ ]:
arr1 = np.array(7,5,9)
arr1

In [16]:
arr1*2

array([   4,    6,   68,   86,   90,  934, 1778])

In [18]:
arr1 =45
arr2 =9879
arr1*arr2

444555